### ISSUE TITLE
[question] Adding living enchantment behaviour without the actual enchantment

### ISSUE THREAD

**Issue by mickelus** [Clownvin/Living-Enchantment#4]
Hello!
I develop tetra and got a request for adding support for living enchantment (https://github.com/mickelus/tetra/issues/48).
I'm currently faking the enchantment setup for tetra items, so that player may apply enchantments to individual parts of a tool or a weapon. I've look around a bit in the code but I could not figure out if it is ossible to add the behaviour of the living enchantment to an item without applying the actual enchantment. Is there an interface that an item could implement or a capability that it could provide to make the item behave as if it had the living enchantment?

**Comment by Clownvin** [comment]
It would be very difficult for you to implement living behaviour without having the item itself enchanted with Living, as that's how the mod checks if it should execute.
I'll see what I can do to assist you.

**Comment by Clownvin** [comment]
Hi, investigation into a solution for you has caused me to realize a new level of potential for this mod, so I'm currently working on a nearly complete rewrite. In the new version, the mod will focus around a Soul capability, instead of enchantments. Enchantments will still exist, almost as they do now, but will be wrapped to a soul when needed.

I'm fairly certain this move will allow you to figure something out, and at the same time has added a huge amount of potential.

I'm going to close this problem, as this new version will be a completely different mod. I don't plan to add any more feature updates to this soon-to-be obsolete version.

**Comment by mickelus** [comment]
Cool!
