### ISSUE TITLE
[REQUEST] Documentation on creating a new personality

### ISSUE THREAD

**Issue by Sunconure11** [Clownvin/Living-Enchantment#5]
Since it appears to be possible, and yet there are some things I don't quite grasp.

**Comment by Clownvin** [comment]
Hi! Personalities are pretty straightforward, you can just copy one of the existing ones, and then replace the text inbetween the tags with a phrase you want the personality to be able to say during the event in the tag. The weight is kinda meaningless to be honest, but if the item is not waiting for talking cooldown, it will try and roll that number to talk. The larger the number, the less likely it is to be able to talk that attempt.

I'm currently starting a heavy rewrite for this mod, and when It's finished I'll provide clearer documentation for creating new personalities (I'll have to since the whole system will probably be different)

**Comment by Clownvin** [comment]
Forgot to mention I'm going to close the issue since I'm not going to update "Living Enchantment" anymore, since It'll be a new mod after the rewrite.
